# permissions for end users to view agentmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentmachine-viewer-role
rules:
- apiGroups:
  - capi-provider.agent-install.openshift.io
  resources:
  - agentmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capi-provider.agent-install.openshift.io
  resources:
  - agentmachines/status
  verbs:
  - get
